<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- NuGet Package Properties -->
    <PackageId>Icot.Shared.Messaging</PackageId>
    <Authors>ICOT Team</Authors>
    <Company>ICOT</Company>
    <Description>ICOT Platform Shared Messaging Library (MassTransit &amp; RabbitMQ integration)</Description>
    <PackageTags>icot;shared;messaging;rabbitmq;masstransit</PackageTags>
    <PackageProjectUrl>https://github.com/pourghadiriHossein/nuget-utils</PackageProjectUrl>
    <RepositoryUrl>https://github.com/pourghadiriHossein/nuget-utils</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.2.0" />
  </ItemGroup>

</Project>
