name: Publish NuGet Packages

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        source-url: https://nuget.pkg.github.com/pourghadiriHossein/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Pack Shared.Kernel
      run: dotnet pack Shared.Kernel/Shared.Kernel.csproj -c Release -p:PackageVersion=1.0.${{ github.run_number }} -p:ContinuousIntegrationBuild=true -o ./artifacts

    - name: Pack Shared.Messaging
      run: dotnet pack Shared.Messaging/Shared.Messaging.csproj -c Release -p:PackageVersion=1.0.${{ github.run_number }} -p:ContinuousIntegrationBuild=true -o ./artifacts

    - name: Push packages to GitHub Packages
      run: dotnet nuget push ./artifacts/*.nupkg --source "github" --skip-duplicate --api-key ${{secrets.GITHUB_TOKEN}}
