name: Publish NuGet Packages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore Shared.Kernel/Shared.Kernel.csproj

    - name: Restore dependencies for Messaging
      run: dotnet restore Shared.Messaging/Shared.Messaging.csproj

    - name: Pack Shared.Kernel
      run: dotnet pack Shared.Kernel/Shared.Kernel.csproj -c Release -p:PackageVersion=1.0.${{ github.run_number }} -p:ContinuousIntegrationBuild=true -o ./artifacts

    - name: Pack Shared.Messaging
      run: dotnet pack Shared.Messaging/Shared.Messaging.csproj -c Release -p:PackageVersion=1.0.${{ github.run_number }} -p:ContinuousIntegrationBuild=true -o ./artifacts

    - name: Push packages to NuGet.org
      run: dotnet nuget push ./artifacts/*.nupkg --source "https://api.nuget.org/v3/index.json" --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}
